name: Build AARCH64 Docker Image with Wheel

on:
  push:
    branches:
      - "**"

env:
  DOCKER_REPOSITORY: quay.io/unstructured-io/paddle
  DOCKER_BUILD_REPOSITORY: quay.io/unstructured-io/paddle
  PIP_VERSION: "22.2.1"
  PYTHON_VERSION: "3.8"

jobs:
  set-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Set Short SHA
        id: set_short_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
  build-arm:
    runs-on: ubuntu-latest
    needs: set-short-sha
    env:
      SHORT_SHA: ${{ needs.set-short-sha.outputs.short_sha }}
    steps:
    - uses: docker/setup-buildx-action@v1
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_IO_ROBOT_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build ARM image
      run: |
        DOCKER_IMAGE_NAME=$DOCKER_BUILD_REPOSITORY:amd-$SHORT_SHA bash paddle/scripts/unstructured_build/create_docker_with_wheel.sh
    - name: Push ARM image
      run: |
        # write to the build repository to cache for the publish-images job
        docker push $DOCKER_BUILD_REPOSITORY:arm-$SHORT_SHA
        docker tag $DOCKER_BUILD_REPOSITORY:arm-$SHORT_SHA $DOCKER_BUILD_REPOSITORY:arm
        docker push $DOCKER_BUILD_REPOSITORY:arm
